version: '3.2'
services:

  neo4j-dev:

  # container_name: neo4j-dev
  ## we use neo4j v3
  build:
      context: neo4j/
      dockerfile: Dockerfile
  
  ## publish ports to have Web UI
  # ports:                    
  #   - '7474:7474'
  #   - '7473:7473'
  #   - '7687:7687'

  ## adds folder with login/password
  # volumes:                  
  #  - $HOME/neo4j/data:/data \