version: '3.2'
services:
  neo4j:
  image: neo4j:3.0          ## we use neo4j v3
  ports:                    ## publish ports to have Web UI
   - "17474:7474"
  volumes:                  ## adds folder with login/password
   - ./db/dbms:/data/dbms