version: '3.1'

services:
  sonarqube-dev:
    # image: sonarqube:7.1
    build:
      context: sonarqube/
      dockerfile: Dockerfile

    # environment:
    #   SONARQUBE_JDBC_USERNAME: root
    #   SONARQUBE_JDBC_PASSWORD: password
    #   SONARQUBE_JDBC_URL: jdbc:mysql://127.0.0.1:3306/testing?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance

    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube

  #   sonarqube:
  # image: sonarqube:5.1.1
  # ports:
  #  - "9000:9000"
  #  - "3306:3306"
  # environment:
  #  - SONARQUBE_JDBC_USERNAME=sonar
  #  - SONARQUBE_JDBC_PASSWORD=sonar
  #  - SONARQUBE_JDBC_URL=jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true 

  #   sonarqube-dev:
  # image: sonarqube:7.1
  # build:
  #     context: sonarqube/
  # environment:
  #   SONARQUBE_JDBC_USERNAME: sonar
  #   SONARQUBE_JDBC_PASSWORD: password
  #   SONARQUBE_JDBC_URL: jdbc:mysql://localhost:3306/testing?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
  # ports:
  #   - 9000:9000
  #   - 9092:9092
  # container_name: sonarqube