#version: '3'

#services:
  # mysql-dev:
    # image: mysql:8.0.2
  # environment:
    # MYSQL_ROOT_PASSWORD: password
    # MYSQL_DATABASE: testing
  # ports:
# _ "3306:3306"


# Use root/example as user/password credentials
version: '3.1'

services:

  # mysql-dev:
  #   image:  mysql:8.0.2
  #   command: --default-authentication-plugin=mysql_native_password
  #   #restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: testing
  #     MYSQL_USER: sonar
  #     MYSQL_PASSWORD: password

  #   ports:
  #     - 3306:3306


  #mysql
  mysql-dev:
    container_name: mysql-dev
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testing
      MYSQL_USER: sonar
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/data/db